const productos = [
  {
    id: 1,
    productName: "Manilla",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 360.0,
    quanty: 1,
    img: "/home/recursos/Manilla-tejida-a-mano-celeste.jpg",
    description: "",
  },
  {
    id: 2,
    productName: "Alcaparras cerámicas",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 25.0,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/2673_2673_alcaparras-ceramica-guaduas-cundinamarca-artesanias-colombia-g.jpg",
    description: "",
  },
  {
    id: 3,
    productName: "Móvil de Gallina Negra",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 35.0,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/36149_15-03-013-c-(5).jpg",
    description: "",
  },
  {
    id: 4,
    productName: "Talla Armadillo Sikuani",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 28.0,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/35138_venta-ig_labs-album4-04-g_n.jpg",
    description: "",
  },
  {
    id: 5,
    productName: "Contenedor Iraca Tapa Morado",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 60.0,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/36155_02-01-030-b-(3).jpg",
    description: "",
  },
  {
    id: 6,
    productName: "Canasto Iraca con Chaquiras",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 70.0,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/36478_11-03-335-g.jpg",
    description: "",
  },
  {
    id: 7,
    productName: "Willys Pitalito Grande Verde",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 20000,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/36109_01-02-049-d.jpg",
    description: "",
  },
  {
    id: 8,
    productName: "Mochila Wayuu Gaza Paleteada",
    community: "xxxx",
    region: "xxxx",
    category: "Joyería",
    price: 34100,
    quanty: 1,
    img: "https://artesaniasdecolombia.com.co/Documentos/Catalogo/35165_11-03-011-k-(2).jpg",
    description: "",
  },
  {
    id: 9,
    productName: "Sombrero Toquilla",
    community: "Artesanos",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/0a/62/74/0a6274348a5f7cf415f6f02a2368a3f2.jpg",
    description: "",
  },
  {
    id: 10,
    productName: "Sombrero Toquilla",
    community: "Artesanos",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/0a/62/74/0a6274348a5f7cf415f6f02a2368a3f2.jpg",
    description: "",
  },
  {
    id: 11,
    productName: "Sombrero Toquilla",
    community: "Artesanos",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/0a/62/74/0a6274348a5f7cf415f6f02a2368a3f2.jpg",
    description: "",
  },
  {
    id: 12,
    productName: "Sombrero Toquilla",
    community: "Artesanos",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/0a/62/74/0a6274348a5f7cf415f6f02a2368a3f2.jpg",
    description: "",
  },
  {
    id: 13,
    productName: "Sombrero Toquilla",
    community: "Artesanos",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/0a/62/74/0a6274348a5f7cf415f6f02a2368a3f2.jpg",
    description: "",
  },
  {
    id: 14,
    productName: "Sombrero Toquilla",
    community: "Artesanos",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/0a/62/74/0a6274348a5f7cf415f6f02a2368a3f2.jpg",
    description: "",
  },
  {
    id: 15,
    productName: "Cartera ",
    community: "Wayuu",
    region: "Nariño",
    category: "Tejidos",
    price: 34100,
    quanty: 1,
    img: "https://i.pinimg.com/736x/6b/36/30/6b3630c4d8066a4436836b37c594ffa6.jpg",
    description: "",
  },

];
